collections:
  - name: ansible.netcommon
    version: "6.1.0"
  - name: arista.eos
    version: "11.0.1"
  - name: cisco.ios
    version: "8.0.0"
  - name: cisco.nxos
    version: "8.0.0"
  - name: community.general
    version: "8.2.0"
