---
- name: NXOS - update usernames on Cisco NXOS devices
  hosts: all
  gather_facts: false
  connection: network_cli

  tasks:
    - name: NXOS - remove old username
      when: change_username | default(false)
      cisco.nxos.nxos_user:
        name: "{{ current_username }}"
        state: absent

    - name: NXOS - add new username
      cisco.nxos.nxos_user:
        name: "{{ new_username }}"
        roles: ["network-admin"]
        configured_password: "{{ new_password }}"

    - name: NXOS - change admin password
      cisco.nxos.nxos_user:
        name: "admin"
        roles: ["network-admin"]
        configured_password: "{{ enable_password }}"
